### ISSUE TITLE
程序出现异常

### ISSUE THREAD

**Issue by moyu284** [heweather/OpenWeatherPlus-Android#7]
我根据你们提供的文档进行修改后，程序运行时爆出了异常，导致程序闪退
12-19 10:02:30.978 3095-3141/? E/com.heweather.owp.crash.CrashHandler: 系统异常退出
    
    java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
        at java.util.ArrayList.get(ArrayList.java:308)
        at com.heweather.owp.view.fragment.WeatherFragment.getWeatherForecast(WeatherFragment.java:536)
        at com.heweather.owp.presenters.impl.WeatherImpl$2.onSuccess(WeatherImpl.java:80)
        at interfaces.heweather.com.interfacesmodule.b.m$1$1.a(WeatherDataImpl.java:81)
        at interfaces.heweather.com.interfacesmodule.c.e$1$3.run(RequestUtil.java:154)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by nicholasFree** [comment]
@moyu284 此问题已修复
